//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.28 at 01:45:55 AM EST 
//


package tamriel.cyrodiil.champion.thor.jaxb.accumulo;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tamriel.cyrodiil.champion.thor.jaxb.accumulo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MasterGoalState_QNAME = new QName("", "masterGoalState");
    private final static QName _IngestMB_QNAME = new QName("", "ingestMB");
    private final static QName _Queued_QNAME = new QName("", "queued");
    private final static QName _Query_QNAME = new QName("", "query");
    private final static QName _QueryMB_QNAME = new QName("", "queryMB");
    private final static QName _DeadTabletServers_QNAME = new QName("", "deadTabletServers");
    private final static QName _BadTabletServers_QNAME = new QName("", "badTabletServers");
    private final static QName _Running_QNAME = new QName("", "running");
    private final static QName _Queryrate_QNAME = new QName("", "queryrate");
    private final static QName _Scans_QNAME = new QName("", "scans");
    private final static QName _TabletServersShuttingDown_QNAME = new QName("", "tabletServersShuttingDown");
    private final static QName _LastContact_QNAME = new QName("", "lastContact");
    private final static QName _Ingest_QNAME = new QName("", "ingest");
    private final static QName _TableId_QNAME = new QName("", "tableId");
    private final static QName _Diskrate_QNAME = new QName("", "diskrate");
    private final static QName _QueryByteRate_QNAME = new QName("", "queryByteRate");
    private final static QName _Scansessions_QNAME = new QName("", "scansessions");
    private final static QName _Numentries_QNAME = new QName("", "numentries");
    private final static QName _UnassignedTablets_QNAME = new QName("", "unassignedTablets");
    private final static QName _Ingestrate_QNAME = new QName("", "ingestrate");
    private final static QName _Hostname_QNAME = new QName("", "hostname");
    private final static QName _IngestByteRate_QNAME = new QName("", "ingestByteRate");
    private final static QName _Tablets_QNAME = new QName("", "tablets");
    private final static QName _OnlineTablets_QNAME = new QName("", "onlineTablets");
    private final static QName _Recs_QNAME = new QName("", "recs");
    private final static QName _RecsInMemory_QNAME = new QName("", "recsInMemory");
    private final static QName _Holdtime_QNAME = new QName("", "holdtime");
    private final static QName _MasterState_QNAME = new QName("", "masterState");
    private final static QName _DeadLoggers_QNAME = new QName("", "deadLoggers");
    private final static QName _Tablename_QNAME = new QName("", "tablename");
    private final static QName _Osload_QNAME = new QName("", "osload");
    private final static QName _TableState_QNAME = new QName("", "tableState");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tamriel.cyrodiil.champion.thor.jaxb.accumulo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Server }
     * 
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link Totals }
     * 
     */
    public Totals createTotals() {
        return new Totals();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Stats }
     * 
     */
    public Stats createStats() {
        return new Stats();
    }

    /**
     * Create an instance of {@link Major }
     * 
     */
    public Major createMajor() {
        return new Major();
    }

    /**
     * Create an instance of {@link Compactions }
     * 
     */
    public Compactions createCompactions() {
        return new Compactions();
    }

    /**
     * Create an instance of {@link Minor }
     * 
     */
    public Minor createMinor() {
        return new Minor();
    }

    /**
     * Create an instance of {@link MajorCompactions }
     * 
     */
    public MajorCompactions createMajorCompactions() {
        return new MajorCompactions();
    }

    /**
     * Create an instance of {@link Tables }
     * 
     */
    public Tables createTables() {
        return new Tables();
    }

    /**
     * Create an instance of {@link Loggers }
     * 
     */
    public Loggers createLoggers() {
        return new Loggers();
    }

    /**
     * Create an instance of {@link Logger }
     * 
     */
    public Logger createLogger() {
        return new Logger();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "masterGoalState")
    public JAXBElement<String> createMasterGoalState(String value) {
        return new JAXBElement<String>(_MasterGoalState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ingestMB")
    public JAXBElement<Double> createIngestMB(Double value) {
        return new JAXBElement<Double>(_IngestMB_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queued")
    public JAXBElement<Byte> createQueued(Byte value) {
        return new JAXBElement<Byte>(_Queued_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "query")
    public JAXBElement<Double> createQuery(Double value) {
        return new JAXBElement<Double>(_Query_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queryMB")
    public JAXBElement<Double> createQueryMB(Double value) {
        return new JAXBElement<Double>(_QueryMB_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deadTabletServers")
    public JAXBElement<String> createDeadTabletServers(String value) {
        return new JAXBElement<String>(_DeadTabletServers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "badTabletServers")
    public JAXBElement<String> createBadTabletServers(String value) {
        return new JAXBElement<String>(_BadTabletServers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "running")
    public JAXBElement<Byte> createRunning(Byte value) {
        return new JAXBElement<Byte>(_Running_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queryrate")
    public JAXBElement<BigDecimal> createQueryrate(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Queryrate_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scans")
    public JAXBElement<Byte> createScans(Byte value) {
        return new JAXBElement<Byte>(_Scans_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tabletServersShuttingDown")
    public JAXBElement<String> createTabletServersShuttingDown(String value) {
        return new JAXBElement<String>(_TabletServersShuttingDown_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastContact")
    public JAXBElement<Short> createLastContact(Short value) {
        return new JAXBElement<Short>(_LastContact_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ingest")
    public JAXBElement<Double> createIngest(Double value) {
        return new JAXBElement<Double>(_Ingest_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tableId")
    public JAXBElement<String> createTableId(String value) {
        return new JAXBElement<String>(_TableId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "diskrate")
    public JAXBElement<BigDecimal> createDiskrate(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Diskrate_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queryByteRate")
    public JAXBElement<Double> createQueryByteRate(Double value) {
        return new JAXBElement<Double>(_QueryByteRate_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scansessions")
    public JAXBElement<BigDecimal> createScansessions(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Scansessions_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numentries")
    public JAXBElement<Integer> createNumentries(Integer value) {
        return new JAXBElement<Integer>(_Numentries_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unassignedTablets")
    public JAXBElement<Byte> createUnassignedTablets(Byte value) {
        return new JAXBElement<Byte>(_UnassignedTablets_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ingestrate")
    public JAXBElement<Double> createIngestrate(Double value) {
        return new JAXBElement<Double>(_Ingestrate_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostname")
    public JAXBElement<String> createHostname(String value) {
        return new JAXBElement<String>(_Hostname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ingestByteRate")
    public JAXBElement<Double> createIngestByteRate(Double value) {
        return new JAXBElement<Double>(_IngestByteRate_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tablets")
    public JAXBElement<Short> createTablets(Short value) {
        return new JAXBElement<Short>(_Tablets_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "onlineTablets")
    public JAXBElement<Byte> createOnlineTablets(Byte value) {
        return new JAXBElement<Byte>(_OnlineTablets_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recs")
    public JAXBElement<Integer> createRecs(Integer value) {
        return new JAXBElement<Integer>(_Recs_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recsInMemory")
    public JAXBElement<Short> createRecsInMemory(Short value) {
        return new JAXBElement<Short>(_RecsInMemory_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "holdtime")
    public JAXBElement<Byte> createHoldtime(Byte value) {
        return new JAXBElement<Byte>(_Holdtime_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "masterState")
    public JAXBElement<String> createMasterState(String value) {
        return new JAXBElement<String>(_MasterState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deadLoggers")
    public JAXBElement<String> createDeadLoggers(String value) {
        return new JAXBElement<String>(_DeadLoggers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tablename")
    public JAXBElement<String> createTablename(String value) {
        return new JAXBElement<String>(_Tablename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "osload")
    public JAXBElement<BigDecimal> createOsload(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Osload_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tableState")
    public JAXBElement<String> createTableState(String value) {
        return new JAXBElement<String>(_TableState_QNAME, String.class, null, value);
    }

}
