//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.28 at 01:45:55 AM EST 
//


package tamriel.cyrodiil.champion.thor.jaxb.accumulo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}tablename"/>
 *         &lt;element ref="{}tableId"/>
 *         &lt;element ref="{}tableState"/>
 *         &lt;element ref="{}tablets"/>
 *         &lt;element ref="{}onlineTablets"/>
 *         &lt;element ref="{}recs"/>
 *         &lt;element ref="{}recsInMemory"/>
 *         &lt;element ref="{}ingest"/>
 *         &lt;element ref="{}ingestByteRate"/>
 *         &lt;element ref="{}query"/>
 *         &lt;element ref="{}queryByteRate"/>
 *         &lt;element ref="{}majorCompactions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tablename",
    "tableId",
    "tableState",
    "tablets",
    "onlineTablets",
    "recs",
    "recsInMemory",
    "ingest",
    "ingestByteRate",
    "query",
    "queryByteRate",
    "majorCompactions"
})
@XmlRootElement(name = "table")
public class Table {

    @XmlElement(required = true)
    protected String tablename;
    @XmlElement(required = true)
    protected String tableId;
    @XmlElement(required = true)
    protected String tableState;
    protected short tablets;
    protected byte onlineTablets;
    protected int recs;
    protected short recsInMemory;
    protected double ingest;
    protected double ingestByteRate;
    protected double query;
    protected double queryByteRate;
    @XmlElement(required = true)
    protected MajorCompactions majorCompactions;

    /**
     * Gets the value of the tablename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * Sets the value of the tablename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTablename(String value) {
        this.tablename = value;
    }

    /**
     * Gets the value of the tableId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * Sets the value of the tableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableId(String value) {
        this.tableId = value;
    }

    /**
     * Gets the value of the tableState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableState() {
        return tableState;
    }

    /**
     * Sets the value of the tableState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableState(String value) {
        this.tableState = value;
    }

    /**
     * Gets the value of the tablets property.
     * 
     */
    public short getTablets() {
        return tablets;
    }

    /**
     * Sets the value of the tablets property.
     * 
     */
    public void setTablets(short value) {
        this.tablets = value;
    }

    /**
     * Gets the value of the onlineTablets property.
     * 
     */
    public byte getOnlineTablets() {
        return onlineTablets;
    }

    /**
     * Sets the value of the onlineTablets property.
     * 
     */
    public void setOnlineTablets(byte value) {
        this.onlineTablets = value;
    }

    /**
     * Gets the value of the recs property.
     * 
     */
    public int getRecs() {
        return recs;
    }

    /**
     * Sets the value of the recs property.
     * 
     */
    public void setRecs(int value) {
        this.recs = value;
    }

    /**
     * Gets the value of the recsInMemory property.
     * 
     */
    public short getRecsInMemory() {
        return recsInMemory;
    }

    /**
     * Sets the value of the recsInMemory property.
     * 
     */
    public void setRecsInMemory(short value) {
        this.recsInMemory = value;
    }

    /**
     * Gets the value of the ingest property.
     * 
     */
    public double getIngest() {
        return ingest;
    }

    /**
     * Sets the value of the ingest property.
     * 
     */
    public void setIngest(double value) {
        this.ingest = value;
    }

    /**
     * Gets the value of the ingestByteRate property.
     * 
     */
    public double getIngestByteRate() {
        return ingestByteRate;
    }

    /**
     * Sets the value of the ingestByteRate property.
     * 
     */
    public void setIngestByteRate(double value) {
        this.ingestByteRate = value;
    }

    /**
     * Gets the value of the query property.
     * 
     */
    public double getQuery() {
        return query;
    }

    /**
     * Sets the value of the query property.
     * 
     */
    public void setQuery(double value) {
        this.query = value;
    }

    /**
     * Gets the value of the queryByteRate property.
     * 
     */
    public double getQueryByteRate() {
        return queryByteRate;
    }

    /**
     * Sets the value of the queryByteRate property.
     * 
     */
    public void setQueryByteRate(double value) {
        this.queryByteRate = value;
    }

    /**
     * Gets the value of the majorCompactions property.
     * 
     * @return
     *     possible object is
     *     {@link MajorCompactions }
     *     
     */
    public MajorCompactions getMajorCompactions() {
        return majorCompactions;
    }

    /**
     * Sets the value of the majorCompactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MajorCompactions }
     *     
     */
    public void setMajorCompactions(MajorCompactions value) {
        this.majorCompactions = value;
    }

}
