//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.30 at 05:22:16 PM EST 
//


package tamriel.cyrodiil.champion.thor.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NimbusServer" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="uiport" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccumuloServer" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="monitorPort" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="dbAccount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="dbPassword" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="zookeepers" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nimbusServer",
    "accumuloServer"
})
@XmlRootElement(name = "Servers")
public class Servers {

    @XmlElement(name = "NimbusServer")
    protected List<Servers.NimbusServer> nimbusServer;
    @XmlElement(name = "AccumuloServer")
    protected List<Servers.AccumuloServer> accumuloServer;

    /**
     * Gets the value of the nimbusServer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nimbusServer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNimbusServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Servers.NimbusServer }
     * 
     * 
     */
    public List<Servers.NimbusServer> getNimbusServer() {
        if (nimbusServer == null) {
            nimbusServer = new ArrayList<Servers.NimbusServer>();
        }
        return this.nimbusServer;
    }

    /**
     * Gets the value of the accumuloServer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accumuloServer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccumuloServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Servers.AccumuloServer }
     * 
     * 
     */
    public List<Servers.AccumuloServer> getAccumuloServer() {
        if (accumuloServer == null) {
            accumuloServer = new ArrayList<Servers.AccumuloServer>();
        }
        return this.accumuloServer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="monitorPort" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="dbAccount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="dbPassword" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="zookeepers" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AccumuloServer {

        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String hostName;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String monitorPort;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String dbAccount;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String dbPassword;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String zookeepers;

        /**
         * Gets the value of the hostName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostName() {
            return hostName;
        }

        /**
         * Sets the value of the hostName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostName(String value) {
            this.hostName = value;
        }

        /**
         * Gets the value of the monitorPort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonitorPort() {
            return monitorPort;
        }

        /**
         * Sets the value of the monitorPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonitorPort(String value) {
            this.monitorPort = value;
        }

        /**
         * Gets the value of the dbAccount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDbAccount() {
            return dbAccount;
        }

        /**
         * Sets the value of the dbAccount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDbAccount(String value) {
            this.dbAccount = value;
        }

        /**
         * Gets the value of the dbPassword property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDbPassword() {
            return dbPassword;
        }

        /**
         * Sets the value of the dbPassword property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDbPassword(String value) {
            this.dbPassword = value;
        }

        /**
         * Gets the value of the zookeepers property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZookeepers() {
            return zookeepers;
        }

        /**
         * Sets the value of the zookeepers property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZookeepers(String value) {
            this.zookeepers = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="uiport" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NimbusServer {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String displayName;
        @XmlAttribute
        protected String hostName;
        @XmlAttribute
        protected Short uiport;
        @XmlAttribute
        protected String username;
        @XmlAttribute
        protected String password;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Gets the value of the hostName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostName() {
            return hostName;
        }

        /**
         * Sets the value of the hostName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostName(String value) {
            this.hostName = value;
        }

        /**
         * Gets the value of the uiport property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getUiport() {
            return uiport;
        }

        /**
         * Sets the value of the uiport property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setUiport(Short value) {
            this.uiport = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

    }

}
